# Homebrew cask for NIGHTCELL 7.
# Generated by tools/release/package-managers.mjs — do not hand-edit.
cask "nightcell7" do
  version "0.2.0"

  on_arm do
    sha256 "a2710e8bbb7c0ce71fa25cb470000240cf2cd5115a9a8e0bf10887a548280732"
    url "https://github.com/profullstack/nightcell7/releases/download/v0.2.0/nightcell7-0.2.0-mac-arm64.dmg",
        verified: "github.com/profullstack/nightcell7/"
  end
  on_intel do
    sha256 "f22f7e8443b22329a29be4ffa8bebbafd7500977ec4c4fef9c66c976ce7d92fe"
    url "https://github.com/profullstack/nightcell7/releases/download/v0.2.0/nightcell7-0.2.0-mac-x64.dmg",
        verified: "github.com/profullstack/nightcell7/"
  end

  name "NIGHTCELL 7"
  desc "Two operatives. Two countries. One manufactured war."
  homepage "https://nightcell7.com"

  app "NIGHTCELL 7.app"

  zap trash: [
    "~/Library/Application Support/NIGHTCELL 7",
    "~/Library/Preferences/com.nightcell7.game.plist",
    "~/Library/Saved Application State/com.nightcell7.game.savedState",
  ]
end
