# Homebrew cask for NIGHTCELL 7.
# Generated by tools/release/package-managers.mjs — do not hand-edit.
cask "nightcell7" do
  version "0.5.1"

  on_arm do
    sha256 "df748c33694c92e1dafecdb4e3a544f47b0ce0beabec79e74da54ac425189c0e"
    url "https://github.com/profullstack/nightcell7/releases/download/v0.5.1/nightcell7-0.5.1-mac-arm64.dmg",
        verified: "github.com/profullstack/nightcell7/"
  end
  on_intel do
    sha256 "f03f5ea172c65cc4d7645da307575242d6f027797145b23106181cd4a9bbec94"
    url "https://github.com/profullstack/nightcell7/releases/download/v0.5.1/nightcell7-0.5.1-mac-x64.dmg",
        verified: "github.com/profullstack/nightcell7/"
  end

  name "NIGHTCELL 7"
  desc "Two operatives. Two countries. One manufactured war."
  homepage "https://nightcell7.com"

  app "NIGHTCELL 7.app"

  zap trash: [
    "~/Library/Application Support/NIGHTCELL 7",
    "~/Library/Preferences/com.nightcell7.game.plist",
    "~/Library/Saved Application State/com.nightcell7.game.savedState",
  ]
end
