# Homebrew cask for NIGHTCELL 7.
# Generated by tools/release/package-managers.mjs — do not hand-edit.
cask "nightcell7" do
  version "0.5.0"

  on_arm do
    sha256 "fdc51714cccf0b89543379f4ab18d8771a2d60f7187739731403c4439978cbf2"
    url "https://github.com/profullstack/nightcell7/releases/download/v0.5.0/nightcell7-0.5.0-mac-arm64.dmg",
        verified: "github.com/profullstack/nightcell7/"
  end
  on_intel do
    sha256 "bc934374e8515e0286055e9551fb845df7303de767b63117ce8b0c40b3918c44"
    url "https://github.com/profullstack/nightcell7/releases/download/v0.5.0/nightcell7-0.5.0-mac-x64.dmg",
        verified: "github.com/profullstack/nightcell7/"
  end

  name "NIGHTCELL 7"
  desc "Two operatives. Two countries. One manufactured war."
  homepage "https://nightcell7.com"

  app "NIGHTCELL 7.app"

  zap trash: [
    "~/Library/Application Support/NIGHTCELL 7",
    "~/Library/Preferences/com.nightcell7.game.plist",
    "~/Library/Saved Application State/com.nightcell7.game.savedState",
  ]
end
